#!/usr/bin/env bash
# A Bash script with the minimum number of commands to automate your fix.
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart
pkill -o nginx
