#!/usr/bin/env bash
#Bash script that stops 4-to_infinity_and_beyond process
#By using the kill command
#Altanative code kill "$(pgrep -f 4-to_infinity_and_beyond)"

pid=$(pgrep "4-to_infinity_and_beyond")
kill "$pid"
