#!/usr/bin/env bash
#Bash script that displays numbers from 1 to 100
	Displays FizzBuzz when the number is a multiple of 3 and 5
#	Displays Fizz when the number is multiple of 3
#	Displays Buzz when the number is a multiple of 5
#	Otherwise, displays the number
#	In a list format

for N in {1..100}
do
	if (( N % 3 == 0 )) && (( N % 5 == 0 ))
	then
		echo "FizzBuzz"
	elif (( N % 3 == 0 ))
	then
		echo "Fizz"
	elif (( N % 5 == 0 ))
	then
		echo "Buzz"
	else
		echo "$N"
	fi
done

