#!/usr/bin/env bash
#Bash script that displays numbers from 1 to 100
	Displays FizzBuzz when the number is a multiple of 3 and 5
#	Displays Fizz when the number is multiple of 3
#	Displays Buzz when the number is a multiple of 5
#	Otherwise, displays the number
#	In a list format

for (( NUM=1; NUM<=100; NUM++ ))
do
	if (( NUM % 3 == 0 )) && (( NUM % 5 == 0 ))
	then
		echo "FizzBuzz"
	elif (( NUM % 3 == 0 ))
	then
		echo "Fizz"
	elif (( NUM % 5 == 0 ))
	then
		echo "Buzz"
	else
		echo "$NUM"
	fi
done

