#!/usr/bin/env bash
#Bash script that displays the content of the file /etc/passwd, using the while loop + IFS.

while IFS=: read -r A1 A2 A3 A4 A5 A6 A7; do
	echo "The user $A1 is part of the $A4 gang, lives in $A6 and rides $A7."
	echo "User ID's place is protected by the passcode $A2, more info about the user here: $A3 $A5"
done < /etc/passwd
