#!/usr/bin/env bash
#Bash script that displays the time for 12 hours and 59 minutes
#	display hours from 0 to 12
#	display minutes from 1 to 59
#Using while nested loops

HOUR=0

while [ $HOUR -le 12 ]
do
	echo "Hour: $HOUR"
	MINUTES=1
	while [ $MINUTES -le 59 ]
	do
		echo "$MINUTES"
		: $(( MINUTES++ ))
	done
	: $(( HOUR++ ))
done
