#!/usr/bin/env bash
#Bash script that displays:
# The content of the current directory
#In a list format
#Where only the part of the name after the first dash is displayed (refer to the example)

LIST=$(ls)

for item in $LIST
do
	echo "$item" | cut -d '-' -f2
done
