#!/usr/bin/env bash
# write a Bash script that accepts one argument
# the script should run the whoami command under the user passed as an argument
# make sure to try your script by passing different users

if [ $# -eq 0 ]; then
  echo "Please provide a user as an argument."
  exit 1
fi

username=$1
sudo -u "$username" whoami

