#!/usr/bin/env bash

# Specify the Gunicorn process name
GUNICORN_PROCESS="gunicorn"

# Get the PIDs of the Gunicorn processes
GUNICORN_PIDS=$(pgrep -f "$GUNICORN_PROCESS")

# Check if there are any Gunicorn processes running
if [ -z "$GUNICORN_PIDS" ]; then
    exit 1
fi

# Gracefully reload each Gunicorn process
for PID in $GUNICORN_PIDS; do
    kill -HUP "$PID"
done

